//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;

public class LambdaHuman : GenericAgent
{
    private float elapsedTime = 0;
    public GenericWeapon weapon;
    public void Start()
    {
        speed = 0.5f; //TODO set zombie speed value
        weapon = Weapons.GetWeapon(Weapons.Weapon.Gun);
        state = States.Idle;
        target = null;
        targetTag = "zombie";
        nextpos = transform.position;
        healthPoints = 100;
        gameObject.tag = "human";
        humanityRate = UnityEngine.Random.Range(40, 100);
    }

    public void Move()
    {
        //TODO write random move function + obstacle avoidance

    }

    public override GenericWeapon Attack(float distance)
    {
        if ((cooldown < 0) && (weapon.Range >= distance))
        {
            Debug.Log(" I, human tried to attack " + targetTag);
            cooldown = weapon.CoolDown;
            return weapon;
        }
        return null;        
    }

    public void Die()
    {
        if (humanityRate < 10)
        {
            //this object become of type zombie
            gameObject.AddComponent<Zombie>();
            Destroy(this);
        }
        else
        {
            //TODO add this death to the human loss score
            Destroy(gameObject);
        }
    }
}


