//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Zombie : GenericAgent
{
	public void Start(){
		speed = 0.5f; //TODO set zombie speed value
		weapon = Weapons.GetWeapon (Weapons.Weapon.Fist);
	}
}


