//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Zombie : GenericAgent
{
    //attributes
    public int agressivityRate = 50;

	public void Start(){
		speed = 0.5f; //TODO set zombie speed value
		weapon = Weapons.GetWeapon (Weapons.Weapon.Fist);
        state = States.Idle;
        target = null;
        targetTag = "human";
        nextpos = transform.position;
        healthPoints = 100;
        gameObject.tag = "zombie";
	}

    public void Move()
    {
        
        //check for neighbourhood and update agressivity rate accorgingly

    }

    public void Attack()
    {
        Debug.Log("Tried to attack " + targetTag);
        //TODO write Attack() function

        //Bite according to agressivity ratio

        //Contaminate
    }

    public void Die()
    {
        // TODO add this zombie death to the zombie counter
        Destroy(gameObject);
    }

}


