//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class GenericWeapon
		//This class implements the weapon type
	{
		public float CoolDown;
		public float Range;
		public float Damages;
		public Dictionary<string, GenericWeapon> weapons = new Dictionary<string, GenericWeapon> ();

		public GenericWeapon (float c, float r, float d) //TODO type is subject to ulteriors changes
		{
			CoolDown = c; 
			Range = r;
			Damages = d;
		}
	}
}

