//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AssemblyCSharp
{
	public class Weapons
	{
		public enum Names{Fist, Gun};
		public Dictionary<Names, GenericWeapon> type = new System.Collections.Generic.Dictionary<Names, GenericWeapon>();

		public Weapons ()
		{
			//type.Add(Fist, new GenericWeapon(5, 5, 10)); // TODO Gamedesign Values subject to future changes
			//type.Add (Gun, new GenericWeapon(3, 15, 15)); //TODO Gamedesign Values subject to future changes
		}
	}
}

