//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Weapons
	{
		public enum Names{Fist, Gun};
		public Dictionary<Names, Weapon> type = new Dictionary<Names, Weapon>;

		public Weapons ()
		{
			type.Add(Fist, GenericWeapon(5, 5, 10)); // Values subject to future changes
			type.Add (Gun, GenericWeapon (3, 15, 15)); //Values subject to future changes
		}
	}
}

